In [ ]:
import pandas as pd
import spacy
from spacy.language import Language
from spacy.tokens import Span
from thefuzz import fuzz, process
from tqdm.auto import tqdm
from newspaper import Article, Config
from newspaper.article import ArticleException
from selenium import webdriver
from selenium.webdriver import ChromeOptions
import threading
from dotenv import load_dotenv
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from thefuzz import fuzz, process
from NewsSentiment import TargetSentimentClassifier
import numpy as np
from typing import Literal
tqdm.pandas()

In [2]:
load_dotenv()
serp_api_key = os.environ.get('SERP_API_KEY')

def get_selenium_html(url):
    with threading.Lock():
        with webdriver.Chrome(options=options) as driver: 
            driver.get(url)
            article_html = driver.page_source
        return article_html

options = ChromeOptions()
options.page_load_strategy = 'eager'
options.add_argument("--headless=new")

config = Config()
config.browser_user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124  Safari/537.36'
config.request_timeout = 20

In [3]:
def parse_url(url) -> str | None:
    try:
        article = Article(url)
        article.download()
        article.parse()

        text = " ".join(article.text.split()[:200])
        if text == '':
            raise LookupError(f"First Attempt: Unable to extact article text for {url}. Retrying...") # if fail, go into second try

        return text
    
    except (ArticleException, LookupError) as e1:
        try:
            if str(e1).find('403') != -1 or isinstance(e1, LookupError):
                article = Article(url, config=config)
                article.download()
                article.parse()

                text = " ".join(article.text.split()[:200])
                if text == '':
                    raise LookupError(f"Second Attempt: Unable to extact article text for {url}. Retrying...") # if fail, go into third try
                else:
                    print(f'Retry succeeded for {url}!')
                
                return text
            
            else:
                print(e1)
                return ''
            
        except (ArticleException, LookupError) as e2:
            if str(e2).find('403') != -1 or isinstance(e2, LookupError):
                article = Article(url, config=config)
                article.download(input_html = get_selenium_html(url))
                article.parse()
                text = " ".join(article.text.split()[:200])
                if text == '':
                    text = ''
                    print(f"Final Attempt: Unable to extact article text for {url}") # if it still fails, can't circumvent.
                else:
                    print(f'Retry succeeded for {url}!')
                
                return text

            else:
                print(e2)
                return ''


def parse_stories_parallel(df, max_threads=80):

    with ThreadPoolExecutor(max_workers=max_threads) as executor:
        results = list(tqdm(executor.map(parse_url, df['url']), total=len(df)))

    df['text'] = results
    df['text'] = df['text'].replace('', pd.NA)
    
    return df

In [ ]:
df_articles = pd.read_csv('elections_opinions.csv')#.sample(10, random_state=42)

df_articles

In [ ]:
df_articles = parse_stories_parallel(df_articles)
df_articles = df_articles.dropna(subset='text').copy()
df_articles

In [5]:
df_corpus = pd.read_json('nivaduck_with_display_names.json')
df_corpus = df_corpus.dropna(subset='display_name')
corpus = df_corpus['display_name'].to_dict()

In [6]:
EST = {
    'BJP',
    'AIADMK',
    #'GOV',
    'NCP',
    'ABVP',
    'TDP',
    'AMMK',
    'JDU',
    'RSS',
    'JDS',
    'MNS',
    'LJP',
    'VHP'
}

OPP = {
    'INC',
    'DMK',
    'AAP',
    'SP',
    'SAMAJWADI',
    'SAMAJWADI ',
    'BJD',
    'TRS',
    'CPIM',
    'AITC',
    'TMC',
    'RJD',
    'AIMIM',
    'JKNC',
    'BSP',
    'JKPDP',
    'JMM',
    'CPIML'
}

In [7]:
nlp = spacy.load('en_core_web_trf')
@Language.component("fuzzy_affiliation")
def fuzzy_affiliates(doc):
    ents = []
    
    for ent in doc.ents:
        if ent.label_ not in {"PERSON", "ORG"}:
            ents.append(ent)
            continue
        
        match = process.extractOne(ent.text, corpus, scorer=fuzz.ratio, score_cutoff=95)

        if not match:
            ents.append(ent)
            continue

        _, _, index =  match
        party = str(df_corpus.loc[index, 'party'])

        if party in EST:
            aff = 'EST'
        elif party in OPP:
            aff = 'OPP'
        else:
            ents.append(ent)
            continue
        
        new_ent = Span(doc, ent.start, ent.end, label=aff)
        ents.append(new_ent)
            
    doc.ents = ents
    return doc

nlp.add_pipe("fuzzy_affiliation", after='ner')

In [8]:
newsmtsc_classifier = TargetSentimentClassifier()

In [9]:
def batch_nlp(df, entity_type:Literal['EST', 'OPP'], batch_size=16):
    #print("[Running NER...]")
    data = []
    texts = list(df['text'])
    #for text in texts: print(text, end='\n\n')
    story_datapoints_tracker = [] # for the story at the i'th index, how many newsmtsc tuples it has
    
    for doc in tqdm(nlp.pipe(texts, batch_size=batch_size), total=len(texts), desc="[Running NER...]"):
        
        data_count = 0

        for ent in doc.ents:
            if ent.label_ == entity_type:
                sentence = ent.sent
                left = doc.text[sentence.start_char : ent.start_char]
                entity_str = ent.text
                right= doc.text[ent.end_char : sentence.end_char]

                left = left[-250:] if len(left) > 250 else left
                right = right[:250] if len(right) > 250 else right
                # handling TooLongTextException - sometimes Newspaper4k won't parse things correctly
                # and you'll end up with the sentence a size of a full article, which newsMTSC will 
                # probably explode on. Hence, truncate

                data.append((left, entity_str, right))
                data_count += 1
        
        story_datapoints_tracker.append(data_count)
    
    if data:
        print("[Running sentiments analysis...]")
        sentiments = newsmtsc_classifier.infer(targets=data, batch_size=batch_size)
        return data, story_datapoints_tracker, sentiments
    
    else:

        print("Could not find ANY relavant entities!")
        return [], [], []


def label_stories(df, entity_type:Literal['EST', 'OPP'],
                  data, story_datapoints_tracker, sentiments):
    print()
    
    label = f'{entity_type}_label'
    ent_col = f'{entity_type}_ents'
    if data == []:
        df[ent_col] = pd.NA
        df[label] = 'unknown'
        return df
    
    labels = []
    all_ents = []
    i = 0

    for k in story_datapoints_tracker:

        vectors = []
        story_ents = set()

        for datapoint, sentiment in zip(data[i:i+k],sentiments[i:i+k]):
            story_ents.add(datapoint[1])
            probs = {item['class_label']: item['class_prob'] for item in sentiment}

            if max(probs.values()) < 0.75: continue

            vector = [probs['positive'], probs['neutral'], probs['negative']]
            print(datapoint)
            print(vector)
            vectors.append(vector)
            
        
        all_ents.append(story_ents)
        
        if not vectors:
            labels.append('unknown')
            i += k
            continue

        print()

        vectors = np.array(vectors)
        article_vec = np.mean(vectors, axis=0)
        #print('Outlet:', story['outlet'])
        #print('URL:', story['url'])
        print('Article Vector:', article_vec)
        class_index = np.argmax(article_vec)

        if class_index == 0:
            labels.append('pro')
        elif class_index == 1:
            labels.append('neutral')
        elif class_index == 2:
            labels.append('anti')
        
        i += k
        print()
        print()

    all_ents = [pd.NA if ents == set() else ents for ents in all_ents]
    
    df[entity_type] = all_ents
    df[label] = labels
    return df

Stance Annotation

Establishment

In [19]:
data, tracker, sents = batch_nlp(df_articles, 'EST')
df_articles = label_stories(df_articles, 'EST', data, tracker, sents)

df_articles

[Running NER...]:   0%|          | 0/1506 [00:00<?, ?it/s]

[Running sentiments analysis...]

Processing batches: 100%|██████████| 205/205 [02:54<00:00,  1.18batch/s]

('The just-concluded Lok Sabha elections were won by ', 'Narendra Modi', ', not the BJP.')
[0.7778029441833496, 0.19371387362480164, 0.028483174741268158]
('This is evident from the exit poll conducted by Lokniti-CSDS, which shows that one-third of the ', 'BJP', ' voters would have chosen a different party had Modi not been the PM candidate.')
[0.08807327598333359, 0.7539703249931335, 0.15795642137527466]
('Not only are most of the ', 'BJP', ' candidates selected by Modi and Amit Shah, but they depend upon the duo after becoming MPs. Advertisement')
[0.09633024036884308, 0.8489124178886414, 0.054757408797740936]
('Not only are most of the BJP candidates selected by Modi and ', 'Amit Shah', ', but they depend upon the duo after becoming MPs. Advertisement')
[0.10985742509365082, 0.8541414141654968, 0.03600120171904564]
('This transformation of a party which took pride in its collegial and democratic decision-making process is probably more damaging at the state-level, where the ', 'BJP', ' faces a greater challenge from its opponents.')
[0.020656704902648926, 0.027376383543014526, 0.9519669413566589]

Article Vector: [0.21854412 0.53562288 0.24583303]


('Many cadres of Left have switched over to ', 'BJP', ' and have given the much-needed last mile connectivity which it was missing earlier')
[0.8084433078765869, 0.13446401059627533, 0.05709270015358925]
('After a record performance in Lok Sabha elections (18 seats / 40% vote share), ', 'BJP', ' has set an ambitious target of dislodging Mamata Banerjee from power in 2021 state elections.')
[0.9086567163467407, 0.056249868124723434, 0.035093363374471664]
('Critics who were giving ', 'BJP', ' not more than 8-10 seats in Lok Sabha were shocked at its tally of 18 seats (+16 vs 2014).')
[0.017088595777750015, 0.08928077667951584, 0.8936306834220886]
('TMC was leading in 161 Assembly seats, 16 more than majority and ', 'BJP', ' in 123 as per trends.')
[0.09073198586702347, 0.7516060471534729, 0.15766195952892303]
('The ', 'BJP', ' did to TMC, what it did to Congress in 2014, successfully managing to brand Mamata as anti-Hindu and pro-minority community.')
[0.8017098903656006, 0.11033479124307632, 0.0879553034901619]

Article Vector: [0.5253261 0.2283871 0.2462868]


('If anything, ', 'BJP', ' seems to have grown in strength since then.')
[0.8276835083961487, 0.13320453464984894, 0.03911195322871208]

Article Vector: [0.82768351 0.13320453 0.03911195]


('Nationalism, protection of cows from slaughter, eradicating poverty, economic reforms, digital technology are today political issues that most identify with the ', 'BJP', ', with Prime Minister Narendra Modi as champion.')
[0.8943567872047424, 0.07770612090826035, 0.027937069535255432]
('Nationalism, protection of cows from slaughter, eradicating poverty, economic reforms, digital technology are today political issues that most identify with the BJP, with Prime Minister ', 'Narendra Modi', ' as champion.')
[0.9552256464958191, 0.02334546111524105, 0.0214289091527462]
('But none of these issues originally belonged to the ', 'BJP', '.')
[0.019328804686665535, 0.8994066715240479, 0.08126447349786758]

Article Vector: [0.62297041 0.33348608 0.04354348]


('He has taken on ', 'Bharatiya Janata Party’s', ' master strategist Amit Shah twice in the recent past and come out trumps.')
[0.07839753478765488, 0.7751651406288147, 0.14643730223178864]
('Grabbing the opportunity Congress inked an alliance with JD (S) to keep ', 'BJP', ' from grabbing power.')
[0.01803775131702423, 0.06389454752206802, 0.9180677533149719]

Article Vector: [0.04821764 0.41952984 0.53225253]


('It is further estimated that out of this amount, more than 50 percent was spent by the ', 'BJP', '.')
[0.04695433750748634, 0.8230671882629395, 0.1299784630537033]

Article Vector: [0.04695434 0.82306719 0.12997846]


('In the Congress, there has been no reflection on the decision to field the pugnacious, entertaining and factually sharp ', 'Raj Thackeray', ' as its de facto chief campaigner through March-April.')
[0.822716474533081, 0.10246419906616211, 0.07481929659843445]
('Post-May, ', 'Raj Thackeray', ' and his Maharashtra Navnirman Sena have shown some purpose.')
[0.960716962814331, 0.027663923799991608, 0.011619100347161293]

Article Vector: [0.89171672 0.06506406 0.0432192 ]


('When Prime Minister ', 'Narendra Modi', ' arrives in Sweden for the first India-Nordic Summit, one question to ask is why such a meeting took so long to materialise.')
[0.04410872235894203, 0.9006524085998535, 0.05523890256881714]

Article Vector: [0.04410872 0.90065241 0.0552389 ]


('Congress leader Siddaramaiah, who blames Prime Minister ', 'Narendra Modi', " and BJP chief Amit Shah for the current upheaval, on Tuesday told media that it was the BJP's sixth attempt to destablise Congress-Janata Dal (Secular) government in last 13 months.")
[0.002911381423473358, 0.00887756422162056, 0.9882110357284546]
('Congress leader Siddaramaiah, who blames Prime Minister Narendra Modi and ', 'BJP', " chief Amit Shah for the current upheaval, on Tuesday told media that it was the BJP's sixth attempt to destablise Congress-Janata Dal (Secular) government in last 13 months.")
[0.0021423932630568743, 0.006576675456017256, 0.9912809729576111]
('Congress leader Siddaramaiah, who blames Prime Minister Narendra Modi and BJP chief ', 'Amit Shah', " for the current upheaval, on Tuesday told media that it was the BJP's sixth attempt to destablise Congress-Janata Dal (Secular) government in last 13 months.")
[0.0026008656714111567, 0.01069375965744257, 0.9867053627967834]
('Congress leader Siddaramaiah, who blames Prime Minister Narendra Modi and BJP chief Amit Shah for the current upheaval, on Tuesday told media that it was the ', 'BJP', "'s sixth attempt to destablise Congress-Janata Dal (Secular) government in last 13 months.")
[0.0021592555567622185, 0.006502292584627867, 0.9913384914398193]
('Allegation flew as Congress accused ', 'BJP', ' of kidnapping them.')
[0.0018461227882653475, 0.014796064235270023, 0.983357846736908]

Article Vector: [0.002332   0.00948927 0.98817874]


('Ram Lal, the longest-serving Bharatiya Janata Party (BJP) general secretary (organisation) is back with the Rashtriya Swayamsevak Sangh (', 'RSS', ').')
[0.06806810945272446, 0.9032176733016968, 0.028714178130030632]
('He was repatriated over the weekend after serving as bridge between the ', 'BJP', ' and the RSS for 12 years.')
[0.06329416483640671, 0.9188687205314636, 0.01783708482980728]
('He was repatriated over the weekend after serving as bridge between the BJP and the ', 'RSS', ' for 12 years.')
[0.05269018933176994, 0.9226424694061279, 0.024667397141456604]
('It follows a national conclave of ', 'RSS', ' prant pracharaks at Vijayawada in Andhra Pradesh ending on Saturday.')
[0.04829107224941254, 0.9397234916687012, 0.011985456570982933]
('The ', 'RSS', ' conclave decided to increase "our effortsfor the purpose of social transformation."')
[0.7754408717155457, 0.2149883657693863, 0.009570750407874584]
("At the three-day conclave, the RSS leaders sounded uncomfortable with the BJP leaders giving total credit for the party's win to Prime Minister ", 'Narendra Modi', "'s popularity and Union Home Minister Amit Shah's organisational skills.")
[0.8012213706970215, 0.10876496136188507, 0.09001368284225464]
("At the three-day conclave, the RSS leaders sounded uncomfortable with the BJP leaders giving total credit for the party's win to Prime Minister Narendra Modi's popularity and Union Home Minister ", 'Amit Shah', "'s organisational skills.")
[0.8175384998321533, 0.07399818301200867, 0.10846330970525742]
('At the end of the conclave, ', 'RSS', ' joint secretary Manmohan Vaidya minced no words in')
[0.028719879686832428, 0.9368859529495239, 0.03439412638545036]

Article Vector: [0.33190802 0.62738623 0.04070575]


('Prime Minister ', 'Narendra Modi', ' shows victory sign as he, along with the party President Amit Shah, arrives at the party headquarters to celebrate their victory in the 2019 Lok Sabha elections, in New Delhi, India, on Thursday, May 23, 2019.')
[0.9285446405410767, 0.05573077127337456, 0.015724562108516693]
('Had the ', 'BJP', ' suffered reverses in these elections, the 2014 mandate could have been dismissed as an aberration.')
[0.011026951484382153, 0.07595668733119965, 0.9130164384841919]
('That the ', 'BJP', ' has not only repeated its 2014 performance, but improved upon it, shows a clear ideological traction for its politics.')
[0.8507993817329407, 0.09224633872509003, 0.05695433169603348]

Article Vector: [0.59679032 0.0746446  0.32856511]


('The Congress with 78 seats (it won two more later in bypolls) and JD(S) with 37 seats decided to form an alliance to keep the ', 'BJP', ' out of power.')
[0.026677334681153297, 0.13836731016635895, 0.8349553942680359]

Article Vector: [0.02667733 0.13836731 0.83495539]


('While the ', 'BJP', ' hailed it as a ‘game of karma’, Congress and JD(S) blamed BJP for horse-trading and carrying out Operation Kamala 2.0.')
[0.006984233390539885, 0.020444346591830254, 0.9725714921951294]
('While the BJP hailed it as a ‘game of karma’, Congress and JD(S) blamed ', 'BJP', ' for horse-trading and carrying out Operation Kamala 2.0.')
[0.006984233390539885, 0.020444346591830254, 0.9725714921951294]
('It had been formed to keep the ', 'BJP', ' out of power.')
[0.026692822575569153, 0.18374307453632355, 0.7895641326904297]
('People voted against the Congress in 144 seats (104 ', 'BJP', ', 37 JD(S), 2 Independents, 1 BSP).')
[0.029680920764803886, 0.7819832563400269, 0.1883358359336853]

Article Vector: [0.01758555 0.25165376 0.73076074]


('The 2019 election results have confirmed the rise of the Bharatiya Janata Party (', 'BJP', ') as the new political hegemon in India.')
[0.8185345530509949, 0.1541569083929062, 0.027308575809001923]
('By increasing its majority between 2014 and 2019, the ', 'BJP', ' has proved that its 2014 victory was not an aberration.')
[0.8395197987556458, 0.11251256614923477, 0.04796760156750679]
('The 2019 election results have confirmed the rise of the Bharatiya Janata Party (', 'BJP', ') as the new political hegemon in India.')
[0.8185345530509949, 0.1541569083929062, 0.027308575809001923]

Article Vector: [0.82552963 0.14027546 0.03419492]


('Karnataka Assembly Speaker KR Ramesh Kumar on Sunday relieved Chief Minister ', 'BS Yediyurappa', ' of a major headache by disqualifying remaining 14 rebel Congress-Janata Dal (Secular) MLAs.')
[0.015007993206381798, 0.05762716010212898, 0.9273647665977478]

Article Vector: [0.01500799 0.05762716 0.92736477]


('The ', 'BJP', ' made its Dalit leader Udit Raj, the vocal MP from North West Delhi, wait too long for the ticket only to deny it at the last moment.')
[0.03337450325489044, 0.8028144836425781, 0.16381096839904785]
('Udit Raj later joined the Congress, saying the ', 'BJP', ' wants its Dalit leaders to remain ‘ deaf and dumb’ .')
[0.02737460657954216, 0.21486897766590118, 0.7577564120292664]
('His shift to the Upper House is part of the seat-sharing agreement between his Lok Janshakti Party, and the allies ', 'BJP', ' and JDU in Bihar.')
[0.12279792129993439, 0.8564561605453491, 0.02074592560529709]

Article Vector: [0.06118234 0.62471321 0.31410444]


('BJP national president ', 'Amit Shah', '’s brazenly defiant comments on the Supreme Court’s Sabarimala order should not surprise anyone.')
[0.13029927015304565, 0.0847870483994484, 0.7849136590957642]
('Over the weekend, ', 'Amit Shah', ' in Kannur pledged “rock-solid support” to those protesting against the Supreme Court order allowing women of all ages to enter the Sabarimala temple, and said governments and courts should “give orders that can be implemented”.')
[0.8187876343727112, 0.15815222263336182, 0.023060115054249763]
('Also read: ', 'BJP', ' has two')
[0.023877736181020737, 0.9400938749313354, 0.0360284261405468]

Article Vector: [0.32432155 0.39434438 0.28133407]


('The morale of the ', 'BJP', ' leaders in West Bengal is high, especially after the panchayat elections where the party came second to the ruling Trinamool Congress (TMC).')
[0.85605388879776, 0.11680588126182556, 0.027140291407704353]
('Around 34 per cent seats were uncontested giving the TMC a decisive lead, but the ', 'BJP', ' registered real success by emerging as the main opposition.')
[0.9107754230499268, 0.0611405149102211, 0.028083985671401024]
('But now, the big worry for the ', 'BJP', ' is that it lacks a prominent leader in West Bengal who is popular and acceptable to not only its supporters, but also has a broader audience.')
[0.01367400586605072, 0.030711783096194267, 0.9556142091751099]

Article Vector: [0.59350111 0.06955273 0.33694616]


('“Arun was the quintessential political professional who spoke with every side, every person seeking conversation,” writes Meghnad Desai, in his eloquent column for The Indian Express this Sunday, as he pens a thoughtful eulogy for the late ', 'Arun Jaitley', '.')
[0.961565375328064, 0.02686174400150776, 0.011572886258363724]
('He talks about how, over a career that spanned 44 years, Jaitley had been a confidant to many, with Prime Minister ', 'Narendra Modi', ' perhaps having been his “longest political friend”.')
[0.7542068958282471, 0.17438477277755737, 0.07140836864709854]

Article Vector: [0.85788614 0.10062326 0.04149063]


('Soon after the Lok Sabha elections ended, the Bharatiya Janata Party (', 'BJP', ') began preparations for the Maharashtra and Haryana state elections.')
[0.11961676925420761, 0.8550838828086853, 0.025299442932009697]

Article Vector: [0.11961677 0.85508388 0.02529944]


('Following these actions, the ', 'BJP', ' managed to get to power with the support of 105 of the 208 remaining legislators in the Assembly.')
[0.9277202486991882, 0.05556933209300041, 0.016710417345166206]

Article Vector: [0.92772025 0.05556933 0.01671042]


('Prime Minister ', 'Narendra Modi', ' and NCP chief Sharad Pawar are holding opposite fronts in politics today.')
[0.0866788774728775, 0.8325843811035156, 0.08073680847883224]
('Prime Minister Narendra Modi and NCP chief ', 'Sharad Pawar', ' are holding opposite fronts in politics today.')
[0.0781092569231987, 0.8662812113761902, 0.055609554052352905]
('At such a time came the surprise development of the Enforcement Directorate (ED) booking ', 'Sharad Pawar', ' in a money laundering case.')
[0.007838393561542034, 0.05171707272529602, 0.9404445290565491]
("Sharad Pawar's nephew ", 'Ajit Pawar', ' has also been named in connection with a bank scam and the Narendra Modi government stands accused of political vendetta.')
[0.001965837785974145, 0.02107328735291958, 0.9769608378410339]
("Sharad Pawar's nephew Ajit Pawar has also been named in connection with a bank scam and the ", 'Narendra Modi', ' government stands accused of political vendetta.')
[0.0015990305691957474, 0.0085589699447155, 0.9898419976234436]
('The case is based on an FIR filed by the Mumbai Police naming ', 'Ajit Pawar', ' and 70 others in a case of malfeasance in the Maharashtra State Cooperative Bank.')
[0.001582777127623558, 0.019019922241568565, 0.9793972373008728]
('Congress leader Rahul Gandhi and Shiv Sena leader Sanjay Raut have backed ', 'Sharad Pawar', ' and have linked the action by central agency to the upcoming Maharashtra Assembly election.')
[0.8776678442955017, 0.10916436463594437, 0.013167760334908962]
('Calling the Modi government "vindictive", Rahul Gandhi said booking ', 'Sharad Pawar', ' "reeks of political opportunism".')
[0.011493374593555927, 0.05432947352528572, 0.9341771602630615]
('The ', 'BJP', ' has naturally rejected the allegations of being vindictive and pursuing a political vendetta.')
[0.033919937908649445, 0.08386124670505524, 0.8822187781333923]
('The bonhomie between ', 'Sharad Pawar', ' and Narendra Modi is though old and came to')
[0.13692255318164825, 0.7989839911460876, 0.0640934482216835]
('The bonhomie between Sharad Pawar and ', 'Narendra Modi', ' is though old and came to')
[0.14684748649597168, 0.751500129699707, 0.10165233910083771]

Article Vector: [0.12587503 0.32700673 0.54711822]


('His nephew ', 'Ajit Pawar', ' is also an accused in the case.')
[0.002011812524870038, 0.07419271022081375, 0.9237954616546631]
('Almost daily, there is news of this or that MLA, MLC, corporator, senior leader leaving the party and joining either ', 'BJP', ' or the Shiv Sena.')
[0.03786095604300499, 0.8083124160766602, 0.15382668375968933]

Article Vector: [0.01993638 0.44125256 0.53881107]


('“We will not give him [Ashok Tanwar] entry [into ', 'BJP', '],” asserted Mr. Khattar, speaking in his constituency Karnal last Saturday.')
[0.029602574184536934, 0.9030557870864868, 0.0673416331410408]
('The remarks by Mr. Khattar, who was responding to a question on whether the ', 'BJP', ' had invited the former Congress chief, stood out in sharp contrast with the ruling party’s past electoral strategy in Haryana.')
[0.054129403084516525, 0.756542444229126, 0.18932802975177765]
('In the run-up to the 2014 Lok Sabha elections, the ', 'BJP', ' had managed to rope in high profile leaders from the State: Chaudhary Birender Singh, who had served as a minister in the previous Congress State government headed by Bhupinder Singh Hooda, and Rao Inderjeet Singh, a former Minister of State in the ')
[0.9038422703742981, 0.06887990981340408, 0.027277836576104164]

Article Vector: [0.32919142 0.57615938 0.09464917]


('', 'BJP', ' made it look like the battle was won even before a single vote was cast through several actions – such as engineering defections in NCP and Congress.')
[0.7934535145759583, 0.09971307963132858, 0.10683337599039078]
('It also helped that in ', 'Devendra Fadnavis', ' and Manohar Khattar, BJP had two credible chief ministers to project.')
[0.9136093854904175, 0.07102444767951965, 0.01536619383841753]
('It also helped that in Devendra Fadnavis and Manohar Khattar, ', 'BJP', ' had two credible chief ministers to project.')
[0.9132257699966431, 0.06685652583837509, 0.019917741417884827]
('NCP supremo ', 'Sharad Pawar', ' gamely tried to make a match of it but resembled an old warhorse riding out into the sunset.')
[0.7735916376113892, 0.12686586380004883, 0.09954255074262619]
('If the exit poll findings hold true on counting day tomorrow, it should give ', 'BJP', ' a free hand to push reforms that stimulate growth and create jobs.')
[0.9014950394630432, 0.0639716163277626, 0.034533340483903885]

Article Vector: [0.85907507 0.08568631 0.05523864]


('The ', 'BJP', ' has brazenly cited military operations to score brownie points in domestic politics always, and the claim of a muscular and militarist foreign policy was the mainstay of its campaign this time too.')
[0.1271490752696991, 0.1153835579752922, 0.7574673891067505]

Article Vector: [0.12714908 0.11538356 0.75746739]


('The ', 'BJP', '’s worst nightmare has come true, as the state seems to be headed for a hung assembly.')
[0.006663559004664421, 0.016988413408398628, 0.9763481020927429]
('The ', 'BJP', ' seems to have borne the brunt of Jat anger, unemployment and rural distress in these elections.')
[0.022873202338814735, 0.05358920246362686, 0.9235376715660095]
('As per news reports, ', 'Amit Shah', ' has summoned chief Minister Manohar Lal Khattar to Delhi.')
[0.023728732019662857, 0.9685512781143188, 0.007720055989921093]

Article Vector: [0.01775516 0.3463763  0.63586861]


('In both the assembly elections, the ', 'BJP', ' vote share is down substantially, compared to its Lok Sabha high of just five months ago.')
[0.026093095541000366, 0.1816297471523285, 0.7922770977020264]
('In Haryana, for example, the ', 'BJP', ' had won 58% of the popular vote and all 10 Lok Sabha seats, while leading in as many as 79 assembly segments.')
[0.8656560778617859, 0.10688036680221558, 0.027463620528578758]

,id,indexed_date,language,media_name,media_url,publish_date,title,url,text,EST,EST_label
0,040f2d7778040bedacec572f66446e31c51e5cc6ab2fb3...,2025-07-02 15:51:38.113666+00:00,en,indianexpress.com,indianexpress.com,2019-06-21,One man show,https://indianexpress.com/article/opinion/colu...,The just-concluded Lok Sabha elections were wo...,"{BJP, Narendra Modi, Amit Shah}",neutral
1,8c9b2e13a6d8804482a4834e25af9b51c60218e06920d7...,2025-07-02 15:35:31.872823+00:00,en,dnaindia.com,dnaindia.com,2019-06-21,BJP’s audacious target,https://www.dnaindia.com/analysis/column-bjp-s...,Party has set an ambitious goal of dislodging ...,{BJP},pro
2,3ef9d8469c5dc41b1b0ae8875c065132315a5b0c4a4ffe...,2025-07-02 10:24:58.756950+00:00,en,indiatimes.com,indiatimes.com,2019-06-25,"Yesterday, once more: Mayawati faces tough cha...",https://timesofindia.indiatimes.com/blogs/toi-...,Bahujan Samaj Party chief Mayawati yesterday a...,{BJP},pro
3,dcd2a88950e4f78a478eaf612e83fd71e8015e2c2ab43d...,2025-07-02 07:08:09.645774+00:00,en,indiatoday.in,indiatoday.in,2019-06-27,"With Narendra Modi taking lead, how BJP is app...",https://www.indiatoday.in/news-analysis/story/...,"Nationalism, protection of cows from slaughter...","{BJP, Narendra Modi}",pro
4,208f5885d54138a55c2671fed309e2e038c34314885170...,2025-07-02 05:56:16.345701+00:00,en,thehindu.com,thehindu.com,2019-06-28,"Will the idea of ‘one nation, one poll’ work i...",https://www.thehindu.com/opinion/op-ed/will-th...,"Last week, when Prime Minister Narendra Modi c...",{Narendra Modi},unknown
...,...,...,...,...,...,...,...,...,...,...,...
1501,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...,Elections are underway in five states — Mizora...,"{BJP, Narendra Modi}",neutral
1502,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...,"In 2018, only one BRS Muslim candidate from Bo...",{BJP},unknown
1503,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...,The Indian National Developmental Inclusive Al...,"{BJP, Bhartiya Janata Party, Narendra Modi}",anti
1504,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...,Madhya Pradesh and 70 assembly constituencies ...,"{BJP, Shivraj Singh Chouhan}",neutral
1505,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...,(This two-part explainer is drawn from a recen...,{BJP},pro

Opposition

In [9]:
data, tracker, sents = batch_nlp(df_articles, 'OPP')
df_articles = label_stories(df_articles, 'OPP', data, tracker, sents)
df_articles.to_parquet('elections_opinions_annotated_new.parquet', index=False)

df_articles

[Running NER...]:   0%|          | 0/1506 [00:00<?, ?it/s]

[Running sentiments analysis...]

Processing batches:  52%|█████▏    | 85/165 [01:51<01:51,  1.40s/batch]Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.
Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.
Processing batches: 100%|██████████| 165/165 [03:33<00:00,  1.29s/batch]

('For the BJP, it means that the party depends on one person more than ever before, like the ', 'Congress', ' used to depend on Indira Gandhi in the 1970s-80s.')
[0.08944577723741531, 0.7634824514389038, 0.14707179367542267]

Article Vector: [0.08944578 0.76348245 0.14707179]


('Party has set an ambitious goal of dislodging ', 'Mamata Banerjee', ' from power in 2021 state elections')
[0.02123161032795906, 0.054406359791755676, 0.924362063407898]
('After a record performance in Lok Sabha elections (18 seats / 40% vote share), BJP has set an ambitious target of dislodging ', 'Mamata Banerjee', ' from power in 2021 state elections.')
[0.03699560463428497, 0.07657863944768906, 0.886425793170929]
('Even if TMC and ', 'Congress', ' would have contested together BJP would have still won 12 seats.')
[0.037528567016124725, 0.9170374274253845, 0.045433953404426575]
('The BJP did to TMC, what it did to ', 'Congress', ' in 2014, successfully managing to brand Mamata as anti-Hindu and pro-minority community.')
[0.08047576993703842, 0.883500337600708, 0.0360238179564476]

Article Vector: [0.04405789 0.48288069 0.47306141]


('Bahujan Samaj Party chief ', 'Mayawati', ' yesterday announced that the party in future will fight elections on its own.')
[0.22686845064163208, 0.7593706250190735, 0.013760900124907494]
('The announcement came a day after the party’s all-India meeting in Lucknow and ends a short-lived alliance with ', 'Samajwadi Party', ' for the 2019 general election.')
[0.041569486260414124, 0.8473320007324219, 0.11109848320484161]
('', 'Mayawati', ' hasn’t put her best foot forward in dealing with this situation.')
[0.010614088736474514, 0.023939460515975952, 0.9654464721679688]

Article Vector: [0.09301734 0.54354736 0.36343529]


('They were all ', 'Congress', "'s issues.")
[0.07007560133934021, 0.9101249575614929, 0.019799401983618736]
('When India got independence, the ', 'Congress', ' was symbol of nationalism and talked about bringing development to the country.')
[0.9358363747596741, 0.045820631086826324, 0.018342943862080574]
('The ', 'Congress', ' had been the ruling party at the Centre for 55 of nearly 73 years post-independence period.')
[0.16774982213974, 0.7982645630836487, 0.03398564085364342]
("In 1971 Lok Sabha election, garibi hatao (eradicate poverty) was the poll slogan of Indira Gandhi's ", 'Congress', '.')
[0.07620200514793396, 0.8853529691696167, 0.038445089012384415]

Article Vector: [0.31246595 0.65989078 0.02764327]


('In a discussion moderated by Anuradha Raman , ', 'Tiruchi Siva', ' and Jagdeep S. Chhokar speak of the implications of the proposed move.')
[0.043111201375722885, 0.9531809091567993, 0.0037079593166708946]
('When Prime Minister Modi floated the idea of ‘one nation, one poll’ yet again and invited the Opposition for a discussion last week, many prominent parties, including the ', 'DMK', ', stayed away from the meeting.')
[0.03329549729824066, 0.9192442893981934, 0.04746014252305031]
('', 'Tiruchi Siva', ':')
[0.010461688041687012, 0.983733594417572, 0.005804786458611488]

Article Vector: [0.02895613 0.95205293 0.01899096]


('1989 Indian politics saw a decisive shift when the era of ', 'Congress', ' hegemony ended, and was replaced by a constellation of regional parties.')
[0.035050999373197556, 0.09967314451932907, 0.8652758598327637]

Article Vector: [0.035051   0.09967314 0.86527586]


('Congress leaders call ', 'DK Shivakumar', ' "Sankat Mochan" (the one who eradicates pain, suffering, sorrow).')
[0.919927179813385, 0.03352527320384979, 0.04654761403799057]
('tions by rebel lawmakers Milind Deora, for example, who has quit as Maharashtra chief last week in expectations of a "national role", first tweeted that he had phoned DKS and then stirred himself for a late afternoon drop-by after a huge outcry from ', 'Congress', ' supporters on social media.')
[0.03625812008976936, 0.8635884523391724, 0.10015340894460678]
("On Deora's watch, the ", 'Congress', ' lost all six seats in Mumbai in the recent general elections.')
[0.008331146091222763, 0.0706111341714859, 0.9210576415061951]

Article Vector: [0.32150548 0.32257495 0.35591955]


('', 'DK Shivakumar', ' is Congress’s last resort’.')
[0.1301758885383606, 0.7973466515541077, 0.07247741520404816]
('DK Shivakumar is ', 'Congress', '’s last resort’.')
[0.053370360285043716, 0.8882527351379395, 0.05837688967585564]
('And in this world where MLAs are frequently herded into resorts to shield them from poaching, ', 'Shivakumar', ' is looked up in awe, a regent of resort politics.')
[0.8674653172492981, 0.09545688331127167, 0.0370778813958168]
('The man chosen to keep the alliance flock together was ', 'DK Shivakumar', '.')
[0.8779128193855286, 0.10679002851247787, 0.015297110192477703]

Article Vector: [0.4822311  0.47196157 0.04580732]


('In the ', 'Congress', ', there has been no reflection on the decision to field the pugnacious, entertaining and factually sharp Raj Thackeray as its de facto chief campaigner through March-April.')
[0.03941914066672325, 0.9289552569389343, 0.03162562474608421]
('He then sought a meeting with former ', 'Congress', ' president Sonia Gandhi.')
[0.015475312247872353, 0.9766163229942322, 0.007908268831670284]
('He then sought a meeting with former Congress president ', 'Sonia Gandhi', '.')
[0.029722385108470917, 0.9605050086975098, 0.009772547520697117]

Article Vector: [0.02820561 0.95535886 0.01643548]


('Congress leader ', 'Siddaramaiah', ", who blames Prime Minister Narendra Modi and BJP chief Amit Shah for the current upheaval, on Tuesday told media that it was the BJP's sixth attempt to destablise Congress-Janata Dal (Secular) government in last 13 months.")
[0.04722345247864723, 0.8242192268371582, 0.12855736911296844]
('However, in February the Operations Kamal 3.0, as the ', 'Congress', ' claims, was out in the open.')
[0.013538843020796776, 0.9801670908927917, 0.006294126622378826]
('Seven ', 'Congress', ' MLAs and one JD (S) MLA skipped assembly sessions.')
[0.012426217086613178, 0.8096415400505066, 0.17793218791484833]
('Allegation flew as ', 'Congress', ' accused BJP of kidnapping them.')
[0.0213219802826643, 0.9499849081039429, 0.02869318053126335]

Article Vector: [0.02362762 0.89100319 0.08536922]


('The recent defections of ', 'Congress', ' legislators in Goa and Telangana to the BJP and the TRS respectively and four TDP MPs in the Rajya Sabha joining the BJP seem to pass the anti-defection law test.')
[0.010596276260912418, 0.13676117360591888, 0.8526425957679749]
('One of the MLAs who joined the BJP in Goa had been elected on a ', 'Congress', ' ticket defeating the BJP nominee only two months earlier.')
[0.11476145684719086, 0.8090305328369141, 0.07620801031589508]

Article Vector: [0.06267887 0.47289585 0.4644253 ]


('The ', 'Congress', ' with 78 seats (it won two more later in bypolls) and JD(S) with 37 seats decided to form an alliance to keep the BJP out of power.')
[0.21291206777095795, 0.7577704191207886, 0.02931743860244751]

Article Vector: [0.21291207 0.75777042 0.02931744]


('While the BJP hailed it as a ‘game of karma’, ', 'Congress', ' and JD(S) blamed BJP for horse-trading and carrying out Operation Kamala 2.0.')
[0.037671737372875214, 0.8776285648345947, 0.0846996158361435]
('', 'Rahul Gandhi', ' referred to JD(S) as Janata Dal Sangh Parivar during his poll')
[0.022047488018870354, 0.9670881628990173, 0.010864287614822388]

Article Vector: [0.02985961 0.92235836 0.04778195]


('Out of the five seats won by the CPI (M) and CPI, four are from the state of Tamil Nadu and probably would not have gone to these parties had they not allied with the Dravida Munnetra Kazhagam (', 'DMK', ') in the state.')
[0.07114237546920776, 0.8743017315864563, 0.05455585941672325]

Article Vector: [0.07114238 0.87430173 0.05455586]


('Udit Raj later joined the ', 'Congress', ', saying the BJP wants its Dalit leaders to remain ‘ deaf and dumb’ .')
[0.025382084771990776, 0.9504155516624451, 0.024202397093176842]
('The most popular Dalit face of Indian politics, Bahujan Samaj Party (BSP) president ', 'Mayawati', ', is not contesting the Lok Sabha elections.')
[0.195307195186615, 0.758497416973114, 0.04619549214839935]

Article Vector: [0.11034464 0.85445648 0.03519894]


('The ruling TMC has ', 'Mamata Banerjee', ' who has a solid track record of long struggle against the Left rule, but neither the BJP, nor the Left-Congress combine have any heavyweight leader to lead the electoral battle.')
[0.915155291557312, 0.03658675029873848, 0.04825791344046593]

Article Vector: [0.91515529 0.03658675 0.04825791]


('When ', 'Bahujan Samaj Party', ' leader Mayawati formed a majority government in Uttar Pradesh in 2007, she had broken a 14-year-long coalition jinx.')
[0.8110231757164001, 0.1347004622220993, 0.05427635833621025]
('When Bahujan Samaj Party leader ', 'Mayawati', ' formed a majority government in Uttar Pradesh in 2007, she had broken a 14-year-long coalition jinx.')
[0.8405395150184631, 0.08994405716657639, 0.0695163905620575]
('The BSP had grown from 67 seats that the party won in 1993 when it first experimented with an alliance with ', 'Samajwadi Party', ', to 206 seats in 2007.')
[0.1676066815853119, 0.7787505984306335, 0.053642723709344864]

Article Vector: [0.60638979 0.33446504 0.05914516]


('That is, former Kolkata police commissioner Rajeev Kumar is not the “real target” of the Central Bureau of Investigation but Trinamool Congress chief ', 'Mamata Banerjee', ' is.')
[0.0640273168683052, 0.8850693702697754, 0.05090327933430672]
('The stakes are high for ', 'Mamata Banerjee', ' and with each passing day Rajeev Kumar remaining ‘underground’')
[0.17192411422729492, 0.7592224478721619, 0.06885340809822083]
('If he continues to remain traceless for long it will have an adverse effect on the people of West Bengal and for that ', 'Mamata Banerjee', ' would have to pay a price in the next elections,” said Amal Kumar Mukhopadhyay, former Presidency College principal and political science professor.')
[0.008065749891102314, 0.01514420099556446, 0.9767901301383972]

Article Vector: [0.08133906 0.55314534 0.36551561]


('The vacancies in Vattiyoorkavu, Konni, Ernakulam and Aroor was caused by the resignations of K. Muraleedharan, Adoor Prakash, and Hybee Eaden of the ', 'Congress', ' and A.M. Arif of the Communist Party of India (Marxist) respectively, on being elected to the Lok Sabha.')
[0.03640858829021454, 0.8644380569458008, 0.09915340691804886]

Article Vector: [0.03640859 0.86443806 0.09915341]


('With the Election Commission of India agreeing to defer byelections to 15 of the 17 vacant Assembly seats in Karnataka, the defectors from the ', 'Congress', ' and JD(S) have got a breather.')
[0.01643301732838154, 0.2304520308971405, 0.7531148791313171]

Article Vector: [0.01643302 0.23045203 0.75311488]


('', 'Congress', ' leader Rahul Gandhi and Shiv Sena leader Sanjay Raut have backed Sharad Pawar and have linked the action by central agency to the upcoming Maharashtra Assembly election.')
[0.21500970423221588, 0.7730045318603516, 0.011985774151980877]
('Calling the Modi government "vindictive", ', 'Rahul Gandhi', ' said booking Sharad Pawar "reeks of political opportunism".')
[0.032659027725458145, 0.9315553307533264, 0.03578560799360275]

Article Vector: [0.12383437 0.85227993 0.02388569]


('NCP was formed in May 1999 by Sharad Pawar, PA Sangma, and ', 'Tariq Anwar', ' after they were expelled from the Congress for opposing Italian Sonia Gandhi’s ascendancy to party president post.')
[0.006705338601022959, 0.1631321907043457, 0.8301624655723572]
('NCP was formed in May 1999 by Sharad Pawar, PA Sangma, and Tariq Anwar after they were expelled from the Congress for opposing Italian ', 'Sonia Gandhi', '’s ascendancy to party president post.')
[0.015013101510703564, 0.15354092419147491, 0.8314459919929504]

Article Vector: [0.01085922 0.15833656 0.83080423]


('The Leader of the Opposition, ', 'Rahul Gandhi', ', and others have raised the matter both inside and outside Parliament.')
[0.22051872313022614, 0.7703104615211487, 0.009170783683657646]
('', 'Praveen Chakravarty', ' and Rangarajan R. discuss the question in a conversation moderated by Sreeparna Chakrabarty.')
[0.023443616926670074, 0.9730978012084961, 0.0034585618413984776]
('', 'Praveen Chakravarty', ':')
[0.011273510754108429, 0.9807485342025757, 0.007978045381605625]
('The main issue that the ', 'Congress', ' and the Leader of the Opposition, Rahul Gandhi, have raised about the 2024 Maharashtra Assembly elections is that there was an abnormal, sudden, and almost unexplainable increase in the number of electors.')
[0.06102200597524643, 0.9049302339553833, 0.03404773399233818]
('The main issue that the Congress and the Leader of the Opposition, ', 'Rahul Gandhi', ', have raised about the 2024 Maharashtra Assembly elections is that there was an abnormal, sudden, and almost unexplainable increase in the number of electors.')
[0.16736476123332977, 0.7780114412307739, 0.05462374910712242]

Article Vector: [0.09672452 0.88141969 0.02185577]


('The faction led by former ', 'Haryana Congress', ' president Ashok Tanwar has been completely sidelined not only in deciding affairs related to the upcoming assembly election but also in ticket distribution.')
[0.02125568687915802, 0.8832333087921143, 0.09551101177930832]
('The faction led by former Haryana Congress president ', 'Ashok Tanwar', ' has been completely sidelined not only in deciding affairs related to the upcoming assembly election but also in ticket distribution.')
[0.006758608855307102, 0.08493342250585556, 0.9083079099655151]
('With this allegation, Ashok Tanwar led his supporters to stage a protest outside ', 'Congress', " president Sonia Gandhi's home in New Delhi.")
[0.014619867317378521, 0.9156919121742249, 0.06968819350004196]
('With this allegation, Ashok Tanwar led his supporters to stage a protest outside Congress president ', 'Sonia Gandhi', "'s home in New Delhi.")
[0.014636765234172344, 0.9483774304389954, 0.03698582202196121]
('His complaint that his list of "15 ', 'Congress', ' workers" was ignored by the election management team led by Bhupinder Singh Hooda and Kumari Selja did not have any impact on the second list released by the Congress party.')
[0.019396526739001274, 0.8958032727241516, 0.08480016887187958]
('His complaint that his list of "15 Congress workers" was ignored by the election management team led by Bhupinder Singh Hooda and Kumari Selja did not have any impact on the second list released by the ', 'Congress', ' party.')
[0.019396526739001274, 0.8958032727241516, 0.08480016887187958]
('The two lists -- of 84 and six candidates -- apparently do not feature ', 'Congress', ' leaders considered close to Ashok Tanwar, who was the Haryana Congress president till a month ago when Kumari Selja replaced him.')
[0.03284948319196701, 0.8863847851753235, 0.08076584339141846]
('The two lists -- of 84 and six candidates -- apparently do not feature Congress leaders considered close to ', 'Ashok Tanwar', ', who was the Haryana Congress president till a month ago when Kumari Selja replaced him.')
[0.043987445533275604, 0.876163899898529, 0.07984858751296997]
('The two lists -- of 84 and six candidates -- apparently do not feature Congress leaders considered close to Ashok Tanwar, who was the ', 'Haryana Congress', ' president till a month ago when Kumari Selja replaced him.')
[0.024128451943397522, 0.9491837620735168, 0.02668783813714981]
('The two lists -- of 84 and six candidates -- apparently do not feature Congress leaders considered close to Ashok Tanwar, who was the Haryana Congress president till a month ago when ', 'Kumari Selja', ' replaced him.')
[0.07343098521232605, 0.8291998505592346, 0.09736914932727814]
('The second list of candidates was released by the ', 'Congress', " after Tanwar's protest.")
[0.011173812672495842, 0.9831417798995972, 0.0056844609789550304]
('', 'Ashok Tanwar', ' is sulking almost in the same way Bhupinder Singh Hooda was brooding during 2019 Lok')
[0.012179570272564888, 0.03902845457196236, 0.948792040348053]

Article Vector: [0.02448448 0.76557876 0.20993677]


('Within hours of ', 'Ashok Tanwar', ', the former chief of the Congress in Haryana resigning from his party’s primary membership, BJP leader and State Chief Minister Manohar Lal Khattar put up a ‘no entry’ sign, for the 43-year-old erstwhile Congressman.')
[0.004431664943695068, 0.04517260193824768, 0.9503957033157349]
('The remarks by Mr. Khattar, who was responding to a question on whether the BJP had invited the former ', 'Congress', ' chief, stood out in sharp contrast with the ruling party’s past electoral strategy in Haryana.')
[0.06322764605283737, 0.7947275042533875, 0.14204491674900055]

Article Vector: [0.03382966 0.41995005 0.54622031]


('This was the net outcome of the 90-minute long meeting of the leaders of the ', 'Congress', ', the CPM and the CPI held in New Delhi.')
[0.03062478080391884, 0.9635492563247681, 0.005825846455991268]

Article Vector: [0.03062478 0.96354926 0.00582585]


('At the time of writing this piece (around 5 PM), the BJP was leading in 39, and ', 'Congress', ' in 32 seats.')
[0.0451287105679512, 0.9411635994911194, 0.013707718811929226]

Article Vector: [0.04512871 0.9411636  0.01370772]


('Five years ago when the ', 'Congress', ' contested Haryana Assembly election, it lost badly.')
[0.01111498475074768, 0.1923917829990387, 0.7964932322502136]
('In 2014, ', 'Congress', ' lost Haryana after two consecutive terms in government.')
[0.010073895566165447, 0.09861402213573456, 0.8913120031356812]
('Five years on, the ', 'Congress', ' has won 31 seats and secured a vote share of 28.1 per cent.')
[0.8298652172088623, 0.15112124383449554, 0.01901351846754551]
('But the story of ', 'Congress', "'s comeback in Haryana appears to have been factored on how Dalits voted in this election.")
[0.8039926290512085, 0.13290414214134216, 0.06310325860977173]
('Of these 17 seats, the BJP has won 5, the ', 'Congress', ' 7 and Others 5.')
[0.05334101617336273, 0.930993914604187, 0.015665041282773018]
('Five years ago, the BJP had won 9 of the 17 reserved seats in Haryana, while ', 'Congress', ' and Others')
[0.043103840202093124, 0.9416903853416443, 0.01520584523677826]

Article Vector: [0.29191526 0.40795258 0.30013215]


('', 'Congress', ' won five general elections in a row in the first 20 years of parliamentary elections, had an overwhelming majority in both Houses of Parliament, and won most states in the first three elections.')
[0.8946877121925354, 0.08746246993541718, 0.01784985139966011]

Article Vector: [0.89468771 0.08746247 0.01784985]


('Many in the ', 'Congress', ' yearn for Priyanka Gandhi to come to their rescue, but she has shown no sign of being willing to oblige.')
[0.07248951494693756, 0.8742653727531433, 0.05324508994817734]
('', 'Sonia Gandhi', ' has formed a new group to bring some clarity to Congress policies.')
[0.9618456363677979, 0.03385835140943527, 0.004295969847589731]
('So what should the ', 'Congress', ' do to get back in business?')
[0.10058087110519409, 0.7733783721923828, 0.12604078650474548]
('The better-than-expected performance of the ', 'Congress', ' in Haryana, and of both the Congress and the Nationalist Congress Party in Maharashtra, has led commentators to declare that their brand is not beyond its sell-by date.')
[0.8358833193778992, 0.12543973326683044, 0.03867693990468979]
('The better-than-expected performance of the Congress in Haryana, and of both the ', 'Congress', ' and the Nationalist Congress Party in Maharashtra, has led commentators to declare that their brand is not beyond its sell-by date.')
[0.8358833193778992, 0.12543973326683044, 0.03867693990468979]

Article Vector: [0.56133653 0.38647631 0.05218715]



,id,indexed_date,language,media_name,media_url,publish_date,title,url,text,EST,EST_label,combined_text,vectors,OPP,OPP_label
0,040f2d7778040bedacec572f66446e31c51e5cc6ab2fb3...,2025-07-02 15:51:38.113666+00:00,en,indianexpress.com,indianexpress.com,2019-06-21,One man show,https://indianexpress.com/article/opinion/colu...,The just-concluded Lok Sabha elections were wo...,"{'BJP', 'Narendra Modi', 'Amit Shah'}",neutral,One man show: The just-concluded Lok Sabha ele...,"[-0.04222811, -0.0115666725, 0.023418004, -0.0...",{Congress},neutral
1,8c9b2e13a6d8804482a4834e25af9b51c60218e06920d7...,2025-07-02 15:35:31.872823+00:00,en,dnaindia.com,dnaindia.com,2019-06-21,BJP’s audacious target,https://www.dnaindia.com/analysis/column-bjp-s...,Party has set an ambitious goal of dislodging ...,{'BJP'},pro,BJP’s audacious target: Party has set an ambit...,"[-0.031283606, 0.014232438, 0.022478845, -0.00...","{Congress, Mamata Banerjee}",neutral
2,3ef9d8469c5dc41b1b0ae8875c065132315a5b0c4a4ffe...,2025-07-02 10:24:58.756950+00:00,en,indiatimes.com,indiatimes.com,2019-06-25,"Yesterday, once more: Mayawati faces tough cha...",https://timesofindia.indiatimes.com/blogs/toi-...,Bahujan Samaj Party chief Mayawati yesterday a...,{'BJP'},pro,"Yesterday, once more: Mayawati faces tough cha...","[-0.043734904, -0.032639347, 0.004154884, 0.01...","{Mayawati, Bahujan Samaj Party, Samajwadi Party}",neutral
3,dcd2a88950e4f78a478eaf612e83fd71e8015e2c2ab43d...,2025-07-02 07:08:09.645774+00:00,en,indiatoday.in,indiatoday.in,2019-06-27,"With Narendra Modi taking lead, how BJP is app...",https://www.indiatoday.in/news-analysis/story/...,"Nationalism, protection of cows from slaughter...","{'BJP', 'Narendra Modi'}",pro,"With Narendra Modi taking lead, how BJP is app...","[-0.01779863, 0.021031821, -0.009818159, -0.00...",{Congress},neutral
4,208f5885d54138a55c2671fed309e2e038c34314885170...,2025-07-02 05:56:16.345701+00:00,en,thehindu.com,thehindu.com,2019-06-28,"Will the idea of ‘one nation, one poll’ work i...",https://www.thehindu.com/opinion/op-ed/will-th...,"Last week, when Prime Minister Narendra Modi c...",{'Narendra Modi'},unknown,"Will the idea of ‘one nation, one poll’ work i...","[-0.058923103, -0.005817032, -0.03389539, -0.0...","{DMK, Tiruchi Siva}",neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...,Elections are underway in five states — Mizora...,"{'BJP', 'Narendra Modi'}",neutral,"P Chidambaram writes: Different states, Differ...","[-0.052230738, -0.008890713, 0.06888017, -0.02...",<NA>,unknown
1502,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...,"In 2018, only one BRS Muslim candidate from Bo...",{'BJP'},unknown,Telangana Election: What is Congress' Strategy...,"[-0.05431041, 0.013782984, -0.030381976, -0.00...","{Congress, AIMIM}",neutral
1503,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...,The Indian National Developmental Inclusive Al...,"{'BJP', 'Bhartiya Janata Party', 'Narendra Modi'}",anti,Can INDIA afford to campaign without unifying ...,"[-0.05980835, -0.019375194, -0.046474203, -0.0...","{Congress, Rahul Gandhi, Mehbooba Mufti}",neutral
1504,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...,Madhya Pradesh and 70 assembly constituencies ...,"{'BJP', 'Shivraj Singh Chouhan'}",neutral,The battle for central India: Madhya Pradesh a...,"[-0.0217077, -0.012442368, -0.016473955, -0.03...","{Congress, Bhupesh Baghel, Kamal Nath}",neutral
1505,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...,(This two-part explainer is drawn from a recen...,{'BJP'},pro,State Elections 2023: Mapping Access (In)Equal...,"[-0.07521105, -0.028066846, 0.012543945, 0.043...",{INC},unknown

Article Embeddings

In [ ]:
from sentence_transformers import SentenceTransformer
df_articles = pd.read_csv('elections_opinions_annotated_new.csv')

df_articles

,id,indexed_date,language,media_name,media_url,publish_date,title,url,text,EST,EST_label
0,040f2d7778040bedacec572f66446e31c51e5cc6ab2fb3...,2025-07-02 15:51:38.113666+00:00,en,indianexpress.com,indianexpress.com,2019-06-21,One man show,https://indianexpress.com/article/opinion/colu...,The just-concluded Lok Sabha elections were wo...,"{'BJP', 'Narendra Modi', 'Amit Shah'}",neutral
1,8c9b2e13a6d8804482a4834e25af9b51c60218e06920d7...,2025-07-02 15:35:31.872823+00:00,en,dnaindia.com,dnaindia.com,2019-06-21,BJP’s audacious target,https://www.dnaindia.com/analysis/column-bjp-s...,Party has set an ambitious goal of dislodging ...,{'BJP'},pro
2,3ef9d8469c5dc41b1b0ae8875c065132315a5b0c4a4ffe...,2025-07-02 10:24:58.756950+00:00,en,indiatimes.com,indiatimes.com,2019-06-25,"Yesterday, once more: Mayawati faces tough cha...",https://timesofindia.indiatimes.com/blogs/toi-...,Bahujan Samaj Party chief Mayawati yesterday a...,{'BJP'},pro
3,dcd2a88950e4f78a478eaf612e83fd71e8015e2c2ab43d...,2025-07-02 07:08:09.645774+00:00,en,indiatoday.in,indiatoday.in,2019-06-27,"With Narendra Modi taking lead, how BJP is app...",https://www.indiatoday.in/news-analysis/story/...,"Nationalism, protection of cows from slaughter...","{'BJP', 'Narendra Modi'}",pro
4,208f5885d54138a55c2671fed309e2e038c34314885170...,2025-07-02 05:56:16.345701+00:00,en,thehindu.com,thehindu.com,2019-06-28,"Will the idea of ‘one nation, one poll’ work i...",https://www.thehindu.com/opinion/op-ed/will-th...,"Last week, when Prime Minister Narendra Modi c...",{'Narendra Modi'},unknown
...,...,...,...,...,...,...,...,...,...,...,...
1501,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...,Elections are underway in five states — Mizora...,"{'BJP', 'Narendra Modi'}",neutral
1502,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...,"In 2018, only one BRS Muslim candidate from Bo...",{'BJP'},unknown
1503,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...,The Indian National Developmental Inclusive Al...,"{'BJP', 'Bhartiya Janata Party', 'Narendra Modi'}",anti
1504,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...,Madhya Pradesh and 70 assembly constituencies ...,"{'BJP', 'Shivraj Singh Chouhan'}",neutral
1505,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...,(This two-part explainer is drawn from a recen...,{'BJP'},pro

In [4]:
df_articles['combined_text'] = df_articles['title'].fillna('') + ": " + df_articles['text']

df_articles

,id,indexed_date,language,media_name,media_url,publish_date,title,url,text,EST,EST_label,combined_text
0,040f2d7778040bedacec572f66446e31c51e5cc6ab2fb3...,2025-07-02 15:51:38.113666+00:00,en,indianexpress.com,indianexpress.com,2019-06-21,One man show,https://indianexpress.com/article/opinion/colu...,The just-concluded Lok Sabha elections were wo...,"{'BJP', 'Narendra Modi', 'Amit Shah'}",neutral,One man show: The just-concluded Lok Sabha ele...
1,8c9b2e13a6d8804482a4834e25af9b51c60218e06920d7...,2025-07-02 15:35:31.872823+00:00,en,dnaindia.com,dnaindia.com,2019-06-21,BJP’s audacious target,https://www.dnaindia.com/analysis/column-bjp-s...,Party has set an ambitious goal of dislodging ...,{'BJP'},pro,BJP’s audacious target: Party has set an ambit...
2,3ef9d8469c5dc41b1b0ae8875c065132315a5b0c4a4ffe...,2025-07-02 10:24:58.756950+00:00,en,indiatimes.com,indiatimes.com,2019-06-25,"Yesterday, once more: Mayawati faces tough cha...",https://timesofindia.indiatimes.com/blogs/toi-...,Bahujan Samaj Party chief Mayawati yesterday a...,{'BJP'},pro,"Yesterday, once more: Mayawati faces tough cha..."
3,dcd2a88950e4f78a478eaf612e83fd71e8015e2c2ab43d...,2025-07-02 07:08:09.645774+00:00,en,indiatoday.in,indiatoday.in,2019-06-27,"With Narendra Modi taking lead, how BJP is app...",https://www.indiatoday.in/news-analysis/story/...,"Nationalism, protection of cows from slaughter...","{'BJP', 'Narendra Modi'}",pro,"With Narendra Modi taking lead, how BJP is app..."
4,208f5885d54138a55c2671fed309e2e038c34314885170...,2025-07-02 05:56:16.345701+00:00,en,thehindu.com,thehindu.com,2019-06-28,"Will the idea of ‘one nation, one poll’ work i...",https://www.thehindu.com/opinion/op-ed/will-th...,"Last week, when Prime Minister Narendra Modi c...",{'Narendra Modi'},unknown,"Will the idea of ‘one nation, one poll’ work i..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1501,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...,Elections are underway in five states — Mizora...,"{'BJP', 'Narendra Modi'}",neutral,"P Chidambaram writes: Different states, Differ..."
1502,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...,"In 2018, only one BRS Muslim candidate from Bo...",{'BJP'},unknown,Telangana Election: What is Congress' Strategy...
1503,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...,The Indian National Developmental Inclusive Al...,"{'BJP', 'Bhartiya Janata Party', 'Narendra Modi'}",anti,Can INDIA afford to campaign without unifying ...
1504,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...,Madhya Pradesh and 70 assembly constituencies ...,"{'BJP', 'Shivraj Singh Chouhan'}",neutral,The battle for central India: Madhya Pradesh a...
1505,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...,(This two-part explainer is drawn from a recen...,{'BJP'},pro,State Elections 2023: Mapping Access (In)Equal...

In [5]:
model = SentenceTransformer('all-MiniLM-L6-v2')
df_articles['vectors'] = list(model.encode(df_articles['combined_text'].tolist(), show_progress_bar=True))

df_articles

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/48 [00:00<?, ?it/s]

,id,indexed_date,language,media_name,media_url,publish_date,title,url,text,EST,EST_label,combined_text,vectors
0,040f2d7778040bedacec572f66446e31c51e5cc6ab2fb3...,2025-07-02 15:51:38.113666+00:00,en,indianexpress.com,indianexpress.com,2019-06-21,One man show,https://indianexpress.com/article/opinion/colu...,The just-concluded Lok Sabha elections were wo...,"{'BJP', 'Narendra Modi', 'Amit Shah'}",neutral,One man show: The just-concluded Lok Sabha ele...,"[-0.04222811, -0.0115666725, 0.023418004, -0.0..."
1,8c9b2e13a6d8804482a4834e25af9b51c60218e06920d7...,2025-07-02 15:35:31.872823+00:00,en,dnaindia.com,dnaindia.com,2019-06-21,BJP’s audacious target,https://www.dnaindia.com/analysis/column-bjp-s...,Party has set an ambitious goal of dislodging ...,{'BJP'},pro,BJP’s audacious target: Party has set an ambit...,"[-0.031283606, 0.014232438, 0.022478845, -0.00..."
2,3ef9d8469c5dc41b1b0ae8875c065132315a5b0c4a4ffe...,2025-07-02 10:24:58.756950+00:00,en,indiatimes.com,indiatimes.com,2019-06-25,"Yesterday, once more: Mayawati faces tough cha...",https://timesofindia.indiatimes.com/blogs/toi-...,Bahujan Samaj Party chief Mayawati yesterday a...,{'BJP'},pro,"Yesterday, once more: Mayawati faces tough cha...","[-0.043734904, -0.032639347, 0.004154884, 0.01..."
3,dcd2a88950e4f78a478eaf612e83fd71e8015e2c2ab43d...,2025-07-02 07:08:09.645774+00:00,en,indiatoday.in,indiatoday.in,2019-06-27,"With Narendra Modi taking lead, how BJP is app...",https://www.indiatoday.in/news-analysis/story/...,"Nationalism, protection of cows from slaughter...","{'BJP', 'Narendra Modi'}",pro,"With Narendra Modi taking lead, how BJP is app...","[-0.01779863, 0.021031821, -0.009818159, -0.00..."
4,208f5885d54138a55c2671fed309e2e038c34314885170...,2025-07-02 05:56:16.345701+00:00,en,thehindu.com,thehindu.com,2019-06-28,"Will the idea of ‘one nation, one poll’ work i...",https://www.thehindu.com/opinion/op-ed/will-th...,"Last week, when Prime Minister Narendra Modi c...",{'Narendra Modi'},unknown,"Will the idea of ‘one nation, one poll’ work i...","[-0.058923103, -0.005817032, -0.03389539, -0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...,Elections are underway in five states — Mizora...,"{'BJP', 'Narendra Modi'}",neutral,"P Chidambaram writes: Different states, Differ...","[-0.052230738, -0.008890713, 0.06888017, -0.02..."
1502,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...,"In 2018, only one BRS Muslim candidate from Bo...",{'BJP'},unknown,Telangana Election: What is Congress' Strategy...,"[-0.05431041, 0.013782984, -0.030381976, -0.00..."
1503,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...,The Indian National Developmental Inclusive Al...,"{'BJP', 'Bhartiya Janata Party', 'Narendra Modi'}",anti,Can INDIA afford to campaign without unifying ...,"[-0.05980835, -0.019375194, -0.046474203, -0.0..."
1504,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...,Madhya Pradesh and 70 assembly constituencies ...,"{'BJP', 'Shivraj Singh Chouhan'}",neutral,The battle for central India: Madhya Pradesh a...,"[-0.0217077, -0.012442368, -0.016473955, -0.03..."
1505,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...,(This two-part explainer is drawn from a recen...,{'BJP'},pro,State Elections 2023: Mapping Access (In)Equal...,"[-0.07521105, -0.028066846, 0.012543945, 0.043..."

In [7]:
df_articles.to_parquet('elections_opinions_annotated_new.parquet', index=False)

BERTopic Topic Modeling

In [22]:
%uv pip install --upgrade transformers sentence-transformers huggingface_hub openai bertopic

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Using Python 3.10.20 environment at: /Users/rupsharray/Documents/Ashoka/Research/IndiaMediaLens/IndiaMediaLens/.iml_venv
Resolved 61 packages in 1.04s
⠙ Preparing packages... (0/11)
⠙ Preparing packages... (0/11)------------------     0 B/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 16.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 32.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 48.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 64.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 64.00 KiB/460.86 KiB
pydantic             ------------------------------ 64.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------     0 B/630.37 KiB
pydantic             ------------------------------ 64.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 14.80 KiB/630.37 KiB
pydantic             ------------------------------ 80.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 14.80 KiB/630.37 KiB
pydantic             ------------------------------ 96.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 14.80 KiB/630.37 KiB
pydantic             ------------------------------ 112.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 14.80 KiB/630.37 KiB
pydantic             ------------------------------ 128.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 14.80 KiB/630.37 KiB
pydantic             ------------------------------ 128.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 14.80 KiB/630.37 KiB
pydantic             ------------------------------ 128.00 KiB/460.86 KiB
⠙ Preparing packages... (0/11)------------------ 14.80 KiB/630.37 KiB
pydantic             ------------------------------ 128.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 14.80 KiB/630.37 KiB
⠙ Preparing packages... (0/11)------------------     0 B/1.86 MiB
pydantic             ------------------------------ 128.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 14.80 KiB/630.37 KiB
⠙ Preparing packages... (0/11)------------------     0 B/1.86 MiB
pydantic             ------------------------------ 128.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 14.80 KiB/630.37 KiB
⠙ Preparing packages... (0/11)------------------     0 B/1.86 MiB
pydantic             ------------------------------ 128.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 14.80 KiB/630.37 KiB
⠙ Preparing packages... (0/11)------------------     0 B/1.86 MiB
pydantic             ------------------------------ 191.73 KiB/460.86 KiB
huggingface-hub      ------------------------------ 77.95 KiB/630.37 KiB
openai               ------------------------------     0 B/1.11 MiB
⠙ Preparing packages... (0/11)------------------ 16.00 KiB/1.86 MiB
pydantic             ------------------------------ 224.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 141.95 KiB/630.37 KiB
openai               ------------------------------ 64.00 KiB/1.11 MiB
⠙ Preparing packages... (0/11)------------------ 48.00 KiB/1.86 MiB
pydantic             ------------------------------ 256.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 205.95 KiB/630.37 KiB
openai               ------------------------------ 128.00 KiB/1.11 MiB
⠹ Preparing packages... (6/11)------------------ 96.00 KiB/1.86 MiB
pydantic             ------------------------------ 320.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 253.95 KiB/630.37 KiB
openai               ------------------------------ 176.00 KiB/1.11 MiB
⠹ Preparing packages... (6/11)------------------ 160.00 KiB/1.86 MiB
pydantic             ------------------------------ 368.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 301.84 KiB/630.37 KiB
openai               ------------------------------ 224.00 KiB/1.11 MiB
⠹ Preparing packages... (6/11)------------------ 192.00 KiB/1.86 MiB
pydantic             ------------------------------ 384.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 317.74 KiB/630.37 KiB
openai               ------------------------------ 256.00 KiB/1.11 MiB
⠹ Preparing packages... (6/11)------------------ 208.00 KiB/1.86 MiB
pydantic             ------------------------------ 432.00 KiB/460.86 KiB
huggingface-hub      ------------------------------ 333.95 KiB/630.37 KiB
openai               ------------------------------ 304.00 KiB/1.11 MiB
⠸ Preparing packages... (6/11)------------------ 271.67 KiB/1.86 MiB
huggingface-hub      ------------------------------ 381.95 KiB/630.37 KiB
openai               ------------------------------ 320.00 KiB/1.11 MiB
⠸ Preparing packages... (6/11)------------------ 288.00 KiB/1.86 MiB
huggingface-hub      ------------------------------ 381.95 KiB/630.37 KiB
openai               ------------------------------ 368.00 KiB/1.11 MiB
⠸ Preparing packages... (6/11)------------------ 336.00 KiB/1.86 MiB
huggingface-hub      ------------------------------ 509.95 KiB/630.37 KiB
openai               ------------------------------ 448.00 KiB/1.11 MiB
⠸ Preparing packages... (6/11)------------------ 400.00 KiB/1.86 MiB
huggingface-hub      ------------------------------ 573.95 KiB/630.37 KiB
openai               ------------------------------ 546.12 KiB/1.11 MiB
⠸ Preparing packages... (6/11)------------------ 480.00 KiB/1.86 MiB
openai               ------------------------------ 560.00 KiB/1.11 MiB
⠸ Preparing packages... (6/11)------------------ 528.00 KiB/1.86 MiB
openai               ------------------------------ 640.00 KiB/1.11 MiB
⠼ Preparing packages... (8/11)------------------ 592.00 KiB/1.86 MiB
openai               ------------------------------ 736.00 KiB/1.11 MiB
⠼ Preparing packages... (8/11)------------------ 640.00 KiB/1.86 MiB
openai               ------------------------------ 880.00 KiB/1.11 MiB
⠼ Preparing packages... (8/11)------------------ 736.00 KiB/1.86 MiB
openai               ------------------------------ 992.00 KiB/1.11 MiB
⠼ Preparing packages... (8/11)m----------------- 848.00 KiB/1.86 MiB
openai               ------------------------------ 1.00 MiB/1.11 MiB
⠴ Preparing packages... (8/11)m------------- 1.06 MiB/1.86 MiB
openai               ------------------------------ 1.00 MiB/1.11 MiB
⠴ Preparing packages... (8/11)--------- 1.31 MiB/1.86 MiB
openai               ------------------------------ 1.00 MiB/1.11 MiB
⠴ Preparing packages... (8/11)--------- 1.59 MiB/1.86 MiB
openai               ------------------------------ 1.06 MiB/1.11 MiB
⠴ Preparing packages... (8/11)--------- 1.70 MiB/1.86 MiB
⠴ Preparing packages... (8/11)--------- 1.80 MiB/1.86 MiB
⠴ Preparing packages... (8/11)------------------     0 B/313.65 KiB
⠦ Preparing packages... (10/11)----------------- 16.00 KiB/313.65 KiB
Prepared 11 packages in 1.06s
Uninstalled 11 packages in 336ms
Installed 11 packages in 80ms
 - bertopic==0.15.0
 + bertopic==0.17.4
 - huggingface-hub==0.19.4
 + huggingface-hub==1.11.0
 - jiter==0.13.0
 + jiter==0.14.0
 - openai==0.28.0
 + openai==2.32.0
 - pydantic==2.12.5
 + pydantic==2.13.1
 - pydantic-core==2.41.5
 + pydantic-core==2.46.1
 - pytz==2022.7.1
 + pytz==2026.1.post1
 - sentence-transformers==2.2.2
 + sentence-transformers==5.4.1
 - tokenizers==0.13.3
 + tokenizers==0.22.2
 - transformers==4.30.2
 + transformers==5.5.4
 - tzdata==2025.3
 + tzdata==2026.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%uv pip install --upgrade transformers sentence-transformers huggingface_hub openai bertopic

In [1]:
import pandas as pd
import openai
from bertopic import BERTopic
from bertopic.representation import OpenAI
from sentence_transformers import SentenceTransformer
from umap import UMAP
from sklearn.feature_extraction.text import CountVectorizer
import torch

In [2]:
df_articles = pd.read_parquet('elections_opinions_annotated_new.parquet')

df_articles

,id,indexed_date,language,media_name,media_url,publish_date,title,url,text,EST,EST_label,combined_text,vectors,OPP,OPP_label
0,040f2d7778040bedacec572f66446e31c51e5cc6ab2fb3...,2025-07-02 15:51:38.113666+00:00,en,indianexpress.com,indianexpress.com,2019-06-21,One man show,https://indianexpress.com/article/opinion/colu...,The just-concluded Lok Sabha elections were wo...,"{'BJP', 'Narendra Modi', 'Amit Shah'}",neutral,One man show: The just-concluded Lok Sabha ele...,"[-0.04222811, -0.0115666725, 0.023418004, -0.0...",[Congress],neutral
1,8c9b2e13a6d8804482a4834e25af9b51c60218e06920d7...,2025-07-02 15:35:31.872823+00:00,en,dnaindia.com,dnaindia.com,2019-06-21,BJP’s audacious target,https://www.dnaindia.com/analysis/column-bjp-s...,Party has set an ambitious goal of dislodging ...,{'BJP'},pro,BJP’s audacious target: Party has set an ambit...,"[-0.031283606, 0.014232438, 0.022478845, -0.00...","[Congress, Mamata Banerjee]",neutral
2,3ef9d8469c5dc41b1b0ae8875c065132315a5b0c4a4ffe...,2025-07-02 10:24:58.756950+00:00,en,indiatimes.com,indiatimes.com,2019-06-25,"Yesterday, once more: Mayawati faces tough cha...",https://timesofindia.indiatimes.com/blogs/toi-...,Bahujan Samaj Party chief Mayawati yesterday a...,{'BJP'},pro,"Yesterday, once more: Mayawati faces tough cha...","[-0.043734904, -0.032639347, 0.004154884, 0.01...","[Mayawati, Bahujan Samaj Party, Samajwadi Party]",neutral
3,dcd2a88950e4f78a478eaf612e83fd71e8015e2c2ab43d...,2025-07-02 07:08:09.645774+00:00,en,indiatoday.in,indiatoday.in,2019-06-27,"With Narendra Modi taking lead, how BJP is app...",https://www.indiatoday.in/news-analysis/story/...,"Nationalism, protection of cows from slaughter...","{'BJP', 'Narendra Modi'}",pro,"With Narendra Modi taking lead, how BJP is app...","[-0.01779863, 0.021031821, -0.009818159, -0.00...",[Congress],neutral
4,208f5885d54138a55c2671fed309e2e038c34314885170...,2025-07-02 05:56:16.345701+00:00,en,thehindu.com,thehindu.com,2019-06-28,"Will the idea of ‘one nation, one poll’ work i...",https://www.thehindu.com/opinion/op-ed/will-th...,"Last week, when Prime Minister Narendra Modi c...",{'Narendra Modi'},unknown,"Will the idea of ‘one nation, one poll’ work i...","[-0.058923103, -0.005817032, -0.03389539, -0.0...","[DMK, Tiruchi Siva]",neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,ce0653dfb6ca458d65e587e462ae36e9672f765b21eced...,2023-11-21 00:39:23+00:00,en,indianexpress.com,indianexpress.com,2023-11-19,"P Chidambaram writes: Different states, Differ...",https://indianexpress.com/article/opinion/colu...,Elections are underway in five states — Mizora...,"{'BJP', 'Narendra Modi'}",neutral,"P Chidambaram writes: Different states, Differ...","[-0.052230738, -0.008890713, 0.06888017, -0.02...",None,unknown
1502,cdb5a12056dfb4573b7a95e51a6003dc1803506d306512...,2023-11-20 03:26:07+00:00,en,thequint.com,thequint.com,2023-11-18,Telangana Election: What is Congress' Strategy...,https://www.thequint.com/opinion/telangana-ele...,"In 2018, only one BRS Muslim candidate from Bo...",{'BJP'},unknown,Telangana Election: What is Congress' Strategy...,"[-0.05431041, 0.013782984, -0.030381976, -0.00...","[Congress, AIMIM]",neutral
1503,eaabb4162e532903144d582d15b8a8c84a98bcf093fac8...,2023-11-19 02:43:21+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-17,Can INDIA afford to campaign without unifying ...,https://www.hindustantimes.com/opinion/keeping...,The Indian National Developmental Inclusive Al...,"{'BJP', 'Bhartiya Janata Party', 'Narendra Modi'}",anti,Can INDIA afford to campaign without unifying ...,"[-0.05980835, -0.019375194, -0.046474203, -0.0...","[Congress, Rahul Gandhi, Mehbooba Mufti]",neutral
1504,fbc8fc2ce95cde01dfcb9e1002b12e751f033f1341a8ee...,2023-11-18 01:03:34+00:00,en,hindustantimes.com,hindustantimes.com,2023-11-16,The battle for central India,https://www.hindustantimes.com/editorials/the-...,Madhya Pradesh and 70 assembly constituencies ...,"{'BJP', 'Shivraj Singh Chouhan'}",neutral,The battle for central India: Madhya Pradesh a...,"[-0.0217077, -0.012442368, -0.016473955, -0.03...","[Congress, Bhupesh Baghel, Kamal Nath]",neutral
1505,820ba90e19c59150d8bcefd0803c1218bee689f1b63658...,2023-11-17 02:56:08+00:00,en,thequint.com,thequint.com,2023-11-15,State Elections 2023: Mapping Access (In)Equal...,https://www.thequint.com/opinion/state-assembl...,(This two-part explainer is drawn from a recen...,{'BJP'},pro,State Elections 2023: Mapping Access (In)Equal...,"[-0.07521105, -0.028066846, 0.012543945, 0.043...",[INC],unknown

In [84]:
# replicability
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', 
                  random_state=42) # random state is the main setting, the rest are defaults needed
                                   # for BERTopic

vectorizer_model = CountVectorizer(stop_words="english", min_df=2, ngram_range=(1, 2))
# remove english stop words, look at bigrams for topics, + BERTopic default, punctuation removed by default

client = openai.OpenAI(base_url="http://localhost:11434/v1", api_key='ollama')

prompt_label = """
I have a topic that contains the following documents:
[DOCUMENTS]
The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label (not more than 5 words) with appropriate capitalization in the following format:
topic: <topic label>
"""
representation_model = OpenAI(client, model='gemma4:e2b', prompt=prompt_label, generator_kwargs={"reasoning_effort" : "none"})


device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

embedding_model = SentenceTransformer("all-MiniLM-L6-v2", device=device)
embeddings = embedding_model.encode(df_articles['combined_text'].to_list(), show_progress_bar=True, batch_size=64)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    vectorizer_model=vectorizer_model,
    #representation_model=representation_model,

    nr_topics=21, # one extra is for misc, will be dropped
    verbose=True
)

Using device: mps

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/24 [00:00<?, ?it/s]

In [85]:
topics, _ = topic_model.fit_transform(df_articles['combined_text'].to_list(), embeddings)

2026-04-17 10:17:06,810 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-04-17 10:17:08,801 - BERTopic - Dimensionality - Completed ✓
2026-04-17 10:17:08,802 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-04-17 10:17:08,820 - BERTopic - Cluster - Completed ✓
2026-04-17 10:17:08,820 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-04-17 10:17:08,994 - BERTopic - Representation - Completed ✓
2026-04-17 10:17:08,994 - BERTopic - Topic reduction - Reducing number of topics
/Users/rupsharray/Documents/Ashoka/Research/IndiaMediaLens/IndiaMediaLens/.iml_venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/rupsharray/Documents/Ashoka/Research/IndiaMediaLens/IndiaMediaLens/.iml_venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/rupsharray/Documents/Ashoka/Research/IndiaMediaLens/IndiaMediaLens/.iml_venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
2026-04-17 10:17:08,997 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-04-17 10:17:09,173 - BERTopic - Representation - Completed ✓
2026-04-17 10:17:09,173 - BERTopic - Topic reduction - Reduced number of topics from 33 to 21

In [86]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,456,-1_bjp_party_elections_modi,"[bjp, party, elections, modi, india, election,...","[On election eve, a tale of two BJPs 20 years ..."
1,0,426,0_bjp_congress_party_seats,"[bjp, congress, party, seats, elections, state...",[Elections 2024: Why Gujarat Continues To Be B...
2,1,108,1_bengal_west bengal_west_mamata,"[bengal, west bengal, west, mamata, tmc, baner...",[Congress routed in 5 assembly polls. Will Rah...
3,2,63,2_gandhi_congress_rahul_party,"[gandhi, congress, rahul, party, rahul gandhi,...",[Sonia takes the wheel as Congress plumbs new ...
4,3,43,3_tamil_nadu_tamil nadu_dmk,"[tamil, nadu, tamil nadu, dmk, aiadmk, stalin,...",[Tamil Nadu Assembly Elections 2021: The Tamil...
5,4,42,4_election_eci_commission_election commission,"[election, eci, commission, election commissio...",[The Election Commission of India was built on...
6,5,40,5_women_women voters_candidates_cases,"[women, women voters, candidates, cases, voter...",[Increased participation to political exclusio...
7,6,40,6_kashmir_jammu_jammu kashmir_union,"[kashmir, jammu, jammu kashmir, union, 370, as...",[Inserting Pakistan into J&K poll talk makes l...
8,7,35,7_modi_election_prime minister_prime,"[modi, election, prime minister, prime, narend...",[Sagarika Ghose writes: Democracy is not in In...
9,8,32,8_bsp_mayawati_dalit_samaj,"[bsp, mayawati, dalit, samaj, bahujan, samaj p...",[Mayawati derails Dalit politics: Is there red...
10,9,32,9_simultaneous_nation election_simultaneous el...,"[simultaneous, nation election, simultaneous e...",[Opinion: Simultaneous Elections: One thing th...
11,10,26,10_trump_biden_president_presidential,"[trump, biden, president, presidential, donald...",[Donald Trump replaces campaign manager Brad P...
12,11,26,11_farmers_farm_economy_food,"[farmers, farm, economy, food, price, governme...",[Farmers at Delhi borders: Why protest over fa...
13,12,24,12_turnout_voter_voter turnout_phase,"[turnout, voter, voter turnout, phase, urban, ...",[Reading the lower voter turnout scenario: Low...
14,13,23,13_sunak_rishi sunak_rishi_conservative,"[sunak, rishi sunak, rishi, conservative, uk, ...","[Voters believe Rishi Sunak will make good PM,..."
15,14,20,14_brs_telangana_rao_rashtra,"[brs, telangana, rao, rashtra, kcr, rashtra sa...",[The BJP’s pitch in Telangana: The top guns of...
16,15,18,15_ai_media_social media_election,"[ai, media, social media, election, digital, s...",[India's general election 2019 will be the big...
17,16,15,16_pakistan_khan_imran_imran khan,"[pakistan, khan, imran, imran khan, army, shar...",[Can Pakistan break the army’s shackles?: A ma...
18,17,14,17_jharkhand_soren_jmm_seats,"[jharkhand, soren, jmm, seats, tribal, hemant ...",[Jharkhand Polls: Can BJP Survive A 'Sympathy ...
19,18,12,18_muslims_muslim_indian_india,"[muslims, muslim, indian, india, politics, ori...",[The Dynamics of Muslim Political Participatio...
20,19,11,19_temple_ram_ayodhya_ram mandir,"[temple, ram, ayodhya, ram mandir, mandir, ram...",[Opinion: Congress's no to Ram Mandir invite s...

In [87]:
topic_model.visualize_topics()

In [88]:
topic_model.visualize_heatmap()

In [89]:
hierarchical_topics = topic_model.hierarchical_topics(df_articles['combined_text'].to_list())
topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics)

100%|██████████| 19/19 [00:00<00:00, 855.12it/s]

In [91]:
topic_model.visualize_barchart(top_n_topics=20)

In [2]:
%uv pip install "transformers==4.30.2" "sentence-transformers==2.2.2" "huggingface_hub<0.20.0" "openai==0.28.1"

Using Python 3.10.20 environment at: /Users/rupsharray/Documents/Ashoka/Research/IndiaMediaLens/IndiaMediaLens/.iml_venv
Resolved 44 packages in 1.04s
⠙ Preparing packages... (0/1)
⠙ Preparing packages... (0/1)-------------------     0 B/75.15 KiB
⠙ Preparing packages... (0/1)------------------- 16.00 KiB/75.15 KiB
⠙ Preparing packages... (0/1)m------------------ 32.00 KiB/75.15 KiB
⠹ Preparing packages... (0/1)--------------- 39.51 KiB/75.15 KiB
⠹ Preparing packages... (0/1)--------------- 39.51 KiB/75.15 KiB
⠹ Preparing packages... (0/1)[30m----------- 48.00 KiB/75.15 KiB
⠹ Preparing packages... (0/1)---------- 51.82 KiB/75.15 KiB
⠹ Preparing packages... (0/1)---------- 59.46 KiB/75.15 KiB
⠹ Preparing packages... (0/1)---------- 75.15 KiB/75.15 KiB
Prepared 1 package in 218ms
Uninstalled 5 packages in 356ms
Installed 5 packages in 36ms
 - huggingface-hub==1.11.0
 + huggingface-hub==0.19.4
 - openai==2.32.0
 + openai==0.28.1
 - sentence-transformers==5.4.1
 + sentence-transformers==2.2.2
 - tokenizers==0.22.2
 + tokenizers==0.13.3
 - transformers==5.5.4
 + transformers==4.30.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

df = pd.read_json('articles_with_text.json')
df

,id,indexed_date,language,media_name,media_url,publish_date,title,url,text
0,dad963715e6a61d2481cc08d0aabf80a798d7e215bc36f...,1733081328483,en,ndtv.com,ndtv.com,1578960000000,Court Seeks Poll Body's Response On Plea For V...,https://www.ndtv.com/india-news/delhi-high-cou...,New Delhi: Delhi High Court on Monday directed...
1,a896d451b026e5a2c9e53dc2ea244d54e1d151f98f284c...,1733076288554,en,ndtv.com,ndtv.com,1578960000000,Indian-Origin British MP Inches Closer In Race...,https://www.ndtv.com/indians-abroad/indian-ori...,"Lisa Nandy, the Indian-origin British MP, and ..."
2,7bb1dced01bd427af43b311d3dba663d128695ed76163b...,1732968243987,en,ndtv.com,ndtv.com,1579910400000,"On National Voters' Day, PM Express Gratitude ...",https://www.ndtv.com/india-news/on-national-vo...,New Delhi: National Voters' Day or Rashtriya M...
3,b77aa012d1afa704fc1c449361adb64636ea303025a83f...,1732916929212,en,ndtv.com,ndtv.com,1580256000000,"""Bullet, Not Biryani"" For Anurag Thakur's Detr...",https://www.ndtv.com/india-news/delhi-assembly...,New Delhi: Karnataka Minister CT Ravi has back...
4,ffebb78904fec1139f8da6c90f5350146b3e4fda291d92...,1732804308510,en,ndtv.com,ndtv.com,1581292800000,"Behind Kejriwal’s Hanuman Chalisa Moment, A St...",https://www.ndtv.com/blog/behind-kejriwals-han...,"A few days before Delhi voted, a prominent new..."
...,...,...,...,...,...,...,...,...,...
286,a0e9be68ad6af1388d05b8f88b5fa9f4d3f71d0b09cfd9...,1766891832044,en,hindustantimes.com,hindustantimes.com,1766880000000,A bitter irony: Thackerays seek Muslim support...,https://www.hindustantimes.com/cities/mumbai-n...,"In 1992, the Sena was accused of being involve..."
287,fae5a44d732ff8902dfbe89b5420e974d2aed44981c9d6...,1766729986801,en,hindustantimes.com,hindustantimes.com,1766707200000,Myanmar to hold first general election in 5 yr...,https://www.hindustantimes.com/world-news/myan...,Myanmar will hold the first phase of a general...
288,e0a0b3e590fb6ab28fff1ed51351ccb047d8d433d1dc51...,1766629213711,en,hindustantimes.com,hindustantimes.com,1766620800000,"‘Not like Putin, Zelensky coming together’: BJ...",https://www.hindustantimes.com/cities/mumbai-n...,"Chief minister Devendra Fadnavis, deputy chief..."
289,84c7f7f103aba80019fa26e9b2986ea02d387128d97995...,1766542834097,en,hindustantimes.com,hindustantimes.com,1766534400000,NCP factions close to alliance for Pune civic ...,https://www.hindustantimes.com/cities/pune-new...,Leaders from both the NCP and NCP (SP) held a ...
290,b3304c3162b0478892925a4d839274d9f8cb9b7a202ff6...,1766456699576,en,hindustantimes.com,hindustantimes.com,1766448000000,"Post-rout in local polls, Sena (UBT) approache...",https://www.hindustantimes.com/cities/mumbai-n...,Uddhav Thackeray’s priority in the crucial BMC...