#### Imports

In [44]:
import pandas as pd

#### Load Database

In [45]:
event =  'budget'

In [46]:
df = pd.read_csv(f'../{event}.csv')

df = df.drop(columns=['Unnamed: 0'])
# missed removing index column while making the CSVs, sorry!

df

,id,indexed_date,language,media_name,media_url,publish_date,title,url
0,dcb0aeace54a4eff23c9fa6ea824da195afe2dbbff6148...,2025-07-02 15:45:32.191912+00:00,en,hindustantimes.com,hindustantimes.com,2019-06-20,An opposition-mukt India is proof of a looming...,https://www.hindustantimes.com/columns/an-oppo...
1,b88d43ee85abb1ae25e00529c7528157f69f149d05b4d9...,2025-07-02 15:27:50.639512+00:00,en,ndtv.com,ndtv.com,2019-06-21,"Clarity On Taxes, Compliance To Boost Investor...",https://www.ndtv.com/business/budget-2019-clar...
2,761e9e51c74e2de14616846b35710b74a80c1904cd35a9...,2025-07-02 15:23:01.170709+00:00,en,indiatimes.com,indiatimes.com,2019-06-21,FM Nirmala Sitharaman holds pre-budget meeting...,https://economictimes.indiatimes.com/news/econ...
3,2a4e323276083edfedd6385d4e4b5aafc9e28bb0c7bada...,2025-07-02 15:22:24.552426+00:00,en,india.com,india.com,2019-06-21,Sitharaman Meets State Finance Ministers For P...,https://www.india.com/business/finance-ministe...
4,a901e251ff16717c7d9f2b6449c6343abbb7c310daa1eb...,2025-07-02 15:16:46.819178+00:00,en,hindustantimes.com,hindustantimes.com,2019-06-21,"Not Rs 325 cr, give us Rs 6,000 cr, Kejriwal’s...",https://www.hindustantimes.com/india-news/not-...
...,...,...,...,...,...,...,...,...
19032,646292395e078f075961bb81006a3b38cda417118efc9e...,2023-11-15 00:23:31+00:00,en,india.com,india.com,2023-11-13,PM Modi To Launch PM PVTG (Particularly Vulner...,https://www.india.com/news/india/pm-modi-to-la...
19033,16c7f0238069bef4718107bc6cd6e5d3b47366b027f104...,2023-11-13 01:44:12+00:00,en,ndtv.com,ndtv.com,2023-11-11,National Education Day: How Is India Leading I...,https://www.ndtv.com/education/national-educat...
19034,2d7f277cf182f2e2c9c41a7d3516d6ec6f22205cf225f5...,2023-11-13 00:09:45+00:00,en,indiatimes.com,indiatimes.com,2023-02-07,GST on digital services: Budget 2023-24 broade...,https://economictimes.indiatimes.com/small-biz...
19035,7753d0a284ba8f43b17bfa822a5a09068267fdf22f7ca9...,2023-11-12 00:15:06+00:00,en,thehindu.com,thehindu.com,2023-03-03,Programme to upskill construction workers,https://www.thehindu.com/life-and-style/homes-...
19036,633516b6ac880164a55c51a56ee472a6c05130872f244c...,2023-11-12 00:12:23+00:00,en,indiatimes.com,indiatimes.com,2023-02-06,Ease of GST compliance: Still a distant dream,https://economictimes.indiatimes.com/small-biz...

#### Set Up Environment

In [47]:
synonyms = ['opinion', 'editorial', 'column', 'op-ed', 'op ed', 'analysis']

In [48]:
def check_presence(text):
    text = str(text).lower()
    return any(synonym in text for synonym in synonyms)

In [49]:
df_opinions = df[df['title'].apply(check_presence) | df['url'].apply(check_presence)]

df_opinions

,id,indexed_date,language,media_name,media_url,publish_date,title,url
0,dcb0aeace54a4eff23c9fa6ea824da195afe2dbbff6148...,2025-07-02 15:45:32.191912+00:00,en,hindustantimes.com,hindustantimes.com,2019-06-20,An opposition-mukt India is proof of a looming...,https://www.hindustantimes.com/columns/an-oppo...
87,de3fffd04c4bec8454bd43003cb1e9bc92deeaac4f1a4d...,2025-07-02 05:56:09.398395+00:00,en,indianexpress.com,indianexpress.com,2019-06-28,A budget wish-list,https://indianexpress.com/article/opinion/colu...
103,9aaf602fb8d9a150804dbd8676379d9727fd6e55aa44c5...,2025-07-02 04:04:12.393744+00:00,en,dnaindia.com,dnaindia.com,2019-06-29,DNA Edit: Surveillance on NBFCs – RBI has ackn...,https://www.dnaindia.com/analysis/editorial-dn...
123,e46b484a77026ab8091d8496c007f9176be06f1aaab947...,2025-07-02 01:55:21.483412+00:00,en,dnaindia.com,dnaindia.com,2019-07-01,Modi 2.0 needs to fulfil promise held out by A...,https://www.dnaindia.com/analysis/column-modi-...
156,f8d8a51bbfe30a3a9b83f52c369267982ec510974e53e6...,2025-07-01 23:55:08.699376+00:00,en,indianexpress.com,indianexpress.com,2019-07-02,"To improve farm livelihoods, a slew of measure...",https://indianexpress.com/article/opinion/colu...
...,...,...,...,...,...,...,...,...
18978,f77ff60c0e84d1c984aba0163dc86797029034edc584a1...,2023-11-30 03:55:46+00:00,en,thequint.com,thequint.com,2023-11-28,"November, Mandal, and Mandir: The Fall of V P ...",https://www.thequint.com/opinion/november-mand...
18981,126a606b138921ecf4abaeb72aa9d68a9ab4281dbb66ca...,2023-11-27 00:18:18+00:00,en,thehindu.com,thehindu.com,2016-12-21,Budget after demonetisation,https://frontline.thehindu.com/columns/C_P_Cha...
18982,d11d0ed653dd061b10117894aaa242ad0928c51d97b93a...,2023-11-27 00:17:26+00:00,en,thehindu.com,thehindu.com,2022-02-06,Union Budget 2022-23: Government reduces spend...,https://frontline.thehindu.com/columns/C_P_Cha...
19011,f472c494049c2dc9d18a45b40ea64b17a7b19b4e311fe2...,2023-11-25 00:20:23+00:00,en,thehindu.com,thehindu.com,2023-02-02,A raft of concessions amid consolidation: The ...,https://www.thehindu.com/opinion/editorial/a-r...
19025,2ac064572e02826884ca6b86157ea0da491e5dd68e8752...,2023-11-25 00:17:44+00:00,en,thehindu.com,thehindu.com,2023-02-25,Political Line Big Picture: BJP vs Congress am...,https://www.thehindu.com/opinion/columns/bjp-v...

In [50]:
df_opinions.to_csv(f'{event}_opinions.csv', index=False)